### ISSUE TITLE
[Android] - Create README and blog post about app.

### ISSUE THREAD

**Issue by muratcanbur** [gdgistanbul/zumbara-x-android#20]
write a blogpost about app arch.
 write a readme (initial version) for the project

**Comment by yusufcakmak** [comment]
you may use this diagram for blog post
https://drive.google.com/file/d/13SEFvw82y_UDY5OgqVheD0FiOQO3qsUo/view?usp=sharing

**Comment by ElifBon** [comment]
https://medium.com/gdg-istanbul/zumbara-x-android-uygulamas%C4%B1-proje-mimarisi-ee54cfaf434e
